---
- hosts: all
  become: yes

  tasks:
  - name: Add a new user named ansible
    user:
      name: chrony
      shell: /bin/bash
      password: "{{ ansible_password }}"

  - name: Add ansible user to the sudoers
    copy:
      dest: "/etc/sudoers.d/ansible"
      content: "ansible  ALL=(ALL)  NOPASSWD: ALL"

  - name: Deploy SSH Key for management user
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      path: /etc/ssh/authorized_keys/ansible

  - name: Disable password login
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^(#\s*)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
      state: present
      backup: yes

  - name: Disable remote root login
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin' 
      line: 'PermitRootLogin no'
      state: present
      backup: yes
 
    notify: restart sshd

handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted