---
- hosts: all
  remote_user: root
  vars_files:
    - "vars/common.yml"
    - [ "vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml" ]
tasks:
  - name: Performing Tasks for CentOS 7
    include_tasks: centos7.yml
    when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == "7")

  - name: Performing Tasks for CentOS 8
    include_tasks: centos8.yml
    when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == "8")

  - name: Performing Tasks for Redhat 7
    include_tasks: RedHat-7.yml
    when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_major_version == "7")

  - name: Performing Tasks for Redhat 8
    include_tasks: RedHat-8.yml
    when: ansible_facts['distribution'] == 'RedHat' and ansible_distribution_major_version == "8")

  - name: Performing Tasks for Amazon Linux 1
    include_tasks: Amazon-1.yml
    when: ansible_facts['distribution'] == 'Amazon' and ansible_distribution_major_version == "1")

  - name: Performing Tasks for Amazon Linux 2
    include_tasks: Amazon-2.yml
    when: ansible_facts['distribution'] == 'Amazon' and ansible_distribution_major_version == "2")

  - name: Performing Tasks for Debian
    include_tasks: debian10.yml
    when: ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == "10") # Only Debian 10

  - name: Performing Tasks for Ubuntu
    include_tasks: ubuntu20.yml
    when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] == "20") # Only Ubuntu 20.04

  - name: Performing Tasks for Suse
    include_tasks: Suse.yml
    when: ansible_facts['distribution'] == 'Suse'

  - name: "shut down CentOS 6 and Debian 7 systems"
    command: /sbin/shutdown -t now
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
          (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")